# Generated by Django 3.2.4 on 2022-09-16 17:31

import django.core.validators
from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', encrypted_model_fields.fields.EncryptedIntegerField()),
                ('Exp_day', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('Exp_month', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Exp_year', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(2022)])),
                ('Puk_code', models.DecimalField(decimal_places=0, max_digits=8)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Gender', models.IntegerField(choices=[(1, 'Man'), (2, 'Women')], default='Man')),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zipcode', models.CharField(max_length=10)),
                ('Extra1', models.CharField(max_length=255)),
                ('Extra2', models.CharField(max_length=255)),
                ('Extra3', models.CharField(max_length=255)),
                ('Extra4', models.CharField(max_length=255)),
                ('Extra5', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
