# Generated by Django 3.2.4 on 2022-09-19 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220918_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='Batch_name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='batch',
            name='Percent',
            field=models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
