# Generated by Django 3.2.4 on 2022-09-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220918_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_data',
            old_name='Areaf6_code',
            new_name='Area_code',
        ),
    ]
