# Generated by Django 3.2.4 on 2022-09-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_shop_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='Batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_product_list', to='cart.batch'),
        ),
    ]
