# Generated by Django 3.2.4 on 2022-09-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_shop_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Insert_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
