# Generated by Django 3.2.4 on 2022-09-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20220920_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='Area_code',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
