# Generated by Django 3.2.4 on 2022-09-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0010_alter_shop_data_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='Areaf4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Areaf5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Areaf6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='User',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='cart.Shop_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
