# Generated by Django 3.2.4 on 2022-09-30 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0011_auto_20220925_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Checker_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('Checker_status', models.CharField(choices=[('Done', 'Done'), ('Fail', 'Fail')], default='Done', max_length=12)),
                ('Checker_response_text', models.TextField()),
                ('Checker_response_full', models.TextField()),
                ('Checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.checker')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.shop_data')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
