# Generated by Django 3.2.4 on 2022-10-05 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0012_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='Phone',
            field=encrypted_model_fields.fields.EncryptedBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Sold_unsold',
            field=models.CharField(choices=[('UNSOLD', 'UNSOLD'), ('SOLD', 'SOLD'), ('REFUND', 'REFUND'), ('ON_CART', 'ON_CART')], default='UNSOLD', max_length=7),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
