# Generated by Django 3.2.4 on 2022-10-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20221012_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='Supplier_payment_status',
        ),
        migrations.AddField(
            model_name='shop_data',
            name='Supplier_payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=8),
        ),
    ]
