# Generated by Django 3.2.4 on 2022-10-18 08:48

import apps.cart.models
from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_supplier_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='Phone',
            field=encrypted_model_fields.fields.EncryptedCharField(validators=[apps.cart.models.only_int]),
        ),
    ]
