# Generated by Django 3.2.4 on 2022-10-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_shop_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=7),
        ),
    ]
