# Generated by Django 3.2.4 on 2022-10-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_shop_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='Zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
