# Generated by Django 3.2.4 on 2022-10-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_auto_20221018_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='City',
            field=models.CharField(blank=True, default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='Extra5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='State',
            field=models.CharField(blank=True, default='Other', max_length=100),
        ),
    ]
