# Generated by Django 3.2.4 on 2022-10-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_alter_order_history_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_history',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.shop_data'),
        ),
    ]
