# Generated by Django 3.2.4 on 2022-10-22 15:23

import apps.cart.models
from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_auto_20221022_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='Phone',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True, validators=[apps.cart.models.only_int]),
        ),
    ]
