# Generated by Django 4.0.4 on 2022-07-11 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_batch_finish_time_alter_batch_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gate1manage',
            old_name='Gate_Logo_tiny',
            new_name='icon_about_gate',
        ),
        migrations.RenameField(
            model_name='gate2manage',
            old_name='Logo_tiny',
            new_name='icon_about_gate',
        ),
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 15, 26, 25, 195748)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 15, 26, 25, 195748)),
        ),
        migrations.AlterField(
            model_name='gate1manage',
            name='uner_mantatince_messge',
            field=models.CharField(help_text='Enter field under manitainence message', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 15, 26, 25, 193753)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Deposit_Received_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 15, 26, 25, 194750)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Balance_updated_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 15, 26, 25, 194750)),
        ),
    ]
