# Generated by Django 4.0.4 on 2022-07-11 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_gate_logo_tiny_gate1manage_icon_about_gate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('on', 'Register Enabled'), ('off', 'Register Disabled')], default='on', max_length=3)),
                ('Note', models.CharField(default='', help_text='Enter note', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 19, 37, 47, 583959)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 19, 37, 47, 583959)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 19, 37, 47, 582962)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Deposit_Received_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 19, 37, 47, 583959)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Balance_updated_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 19, 37, 47, 583959)),
        ),
    ]
