# Generated by Django 4.0.4 on 2022-07-12 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_message_seen_news_seen_alter_batch_finish_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_manage',
            name='Uner_Mantatince_Messge',
        ),
        migrations.AddField(
            model_name='site_manage',
            name='Under_Maintainance_Message',
            field=models.CharField(default='', help_text='Enter field Under Maintainance Message', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='finish_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 12, 17, 5, 735932)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 12, 17, 5, 735932)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 12, 17, 5, 733904)),
        ),
        migrations.AlterField(
            model_name='site_manage',
            name='Site_Status',
            field=models.CharField(choices=[('on', 'Online'), ('off', 'Under Maintainance')], default='on', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Deposit_Received_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 12, 17, 5, 734934)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='User_Balance_updated_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 12, 17, 5, 734934)),
        ),
    ]
