# Generated by Django 3.2.4 on 2022-07-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_batch_finish_time_alter_batch_start_time_and_more'),
        ('home', '0014_auto_20220714_1227'),
    ]

    operations = [
    ]
